version: 2
updates:
  - package-ecosystem: npm
    directory: /clients/ts
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /clients/wasm
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
